version: "3"

services:
  app:
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: